# Tomcat
server:
  port: 520
  compression:
    enabled: true
    min-response-size: 2048
    mime-types:
      - image/png
      - image/jpeg
      - image/jpg
      - text/html
      - application/javascript
      - text/css
      - application/octet-stream
      - application/json